// Generated by WebFx

module webfx.tools.util.reusablestream {

    // Direct dependencies modules
    requires java.base;

    // Exported packages
    exports dev.webfx.tools.util.reusablestream;
    exports dev.webfx.tools.util.reusablestream.impl;

}