// Generated by WebFx

module webfx.tools {

    // Direct dependencies modules
    requires java.base;
    requires java.xml;
    requires webfx.lib.reusablestream;

    // Exported packages
    exports dev.webfx.buildtool;
    exports dev.webfx.buildtool.modulefiles;
    exports dev.webfx.buildtool.sourcegenerators;
    exports dev.webfx.buildtool.util.javacode;
    exports dev.webfx.buildtool.util.splitfiles;
    exports dev.webfx.buildtool.util.textfile;
    exports dev.webfx.buildtool.util.xml;

}