// Generated by WebFx

module webfx.tools.emultranslator {

    // Direct dependencies modules
    requires java.base;
    requires webfx.platform.shared.json;

    // Exported packages
    exports dev.webfx.tools.emultranslator;

}